### ISSUE TITLE
Implement tinynav.js to collapse nav to select on mobile

### ISSUE THREAD

**Issue by kenlimmj** [jethrokuan/ol#13]
data-spy="affix" currently conflicts with tinynav.js

Need to find a way to unload affix when the columns stack, then load tinynav to convert the menu into a drop down.

**Comment by jethrokuan** [comment]
Jquery remove affix class?

**Comment by kenlimmj** [comment]
Tried it before using enquire.js/breakpoint.js to catch the media-query breakpoint. Didn't work, but that might have been because I was using headjs. Will try again with unobfuscated script tags.

**Comment by kenlimmj** [comment]
Fixed in latest commit to branch <iframe seamless>
