### ISSUE TITLE
Select2 broken; appears to be not included.

### ISSUE THREAD

**Issue by jethrokuan** [jethrokuan/ol#24]

**Comment by kenlimmj** [comment]
Where is select2 used?

**Comment by jethrokuan** [comment]
Is it select2? It's used for the new/edit functions. To select its parent.

**Comment by jethrokuan** [comment]
@kenlimmj No idea why review is requesting for select2, which makes select2 load before jquery. Can look at it?

**Comment by jethrokuan** [comment]
Fixed but have to fix for every page. (And select a bit buggy...)

**Comment by kenlimmj** [comment]
Can we do without?

**Comment by kenlimmj** [comment]
Select2 meant for multi tag selection mainly

**Comment by jethrokuan** [comment]
When the database gets huge, then it's better if we use select2 la.

**Comment by kenlimmj** [comment]
Ok understood.
