### ISSUE TITLE
Add turbolinks

### ISSUE THREAD

**Issue by kenlimmj** [jethrokuan/ol#27]
Consider adding turbolinks.

http://railscasts.com/episodes/390-turbolinks

Will use:

https://github.com/kossnocorp/jquery.turbolinks
https://github.com/rails/turbolinks

Could break some JS though, so leave till everything is done.

**Comment by jethrokuan** [comment]
conflict?

**Comment by kenlimmj** [comment]
oo conflict with?

**Comment by jethrokuan** [comment]
Just doesn't look like it's using turbolinks.

**Comment by kenlimmj** [comment]
Feels faster to me leh. I think can leave it for now. No conflicts observed thus far. Will reopen if something goes kaboom
