### ISSUE TITLE
Resolve conflict between the two devise models

### ISSUE THREAD

**Issue by jethrokuan** [jethrokuan/ol#29]

**Comment by kenlimmj** [comment]
Realized it's not possible to sign in as staff via the user sign in url or form. I'm guessing this is also because of the conflict?

**Comment by jethrokuan** [comment]
staff has a different sign_in page at staffs/sign_in.

**Comment by kenlimmj** [comment]
Yeah. Any chance of integrating the two of them so they use the same form?
