### ISSUE TITLE
Pacman broken again.

### ISSUE THREAD

**Issue by kenlimmj** [jethrokuan/ol#32]
``` javascript

Uncaught TypeError: Object function () {
    var i, newObj = (this instanceof Array) ? [] : {};
    for (i in this) {
        if (i === 'clone') {
            continue;
        }
        if (this[i] && typeof this[i] === "object") {
            newObj[i] = this[i].clone();
        } else {
            newObj[i] = this[i];
        }
    }
    return newObj;
} has no method 'exec' 

```

I will smash the next pacman machine I see.

**Comment by jethrokuan** [comment]
jQuery is not being loaded first. (same error i got last time. Exec is a
method from jquery)

**Comment by kenlimmj** [comment]
jQuery loads first but still throws this problem. 

Tried removing turbolinks too to see if it's causing the error. 

Getting garbled fonts on the readout. Will check to see if it's caused by my updating the fontset

**Comment by kenlimmj** [comment]
Ok found the problem. It's a font thing. That part is fixed. 

Smaller problem hidden within is that my link to the file path for the audio wasn't done properly. 

So if the handler loads at http://localhost:3000/404, it works fine because it finds the audio at assets/audio

But if it loads from http://localhost:3000/pages/404, it fails because it finds the audio at pages/assets/audio. 

Will figure out why <% asset_path('foo') %> doesn't work as intended.
